# Generated by Django 5.2.8 on 2026-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='stage',
            field=models.CharField(choices=[('primary', 'Foundation (Class 8-10)'), ('middle', 'Class 11 & 12'), ('high', 'Competitive / Dropper Batch')], max_length=10),
        ),
    ]
