# Generated by Django 5.2.8 on 2026-09-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_alter_course_duration_alter_course_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
